#ifndef FONCTION_H_INCLUDED
#define FONCTION_H_INCLUDED
#include <string>
using namespace std;


/*
BLABLABLABLABLABLABLABLABLABLABLA
BLABLABLABALBALABLABALBALABLABALB
*/
char GetCaractere ();
/*
BLABLABLABLABLABLABLABLABLABLABLA
BLABLABLABALBALABLABALBALABLABALB
*/
int GetNombreAleatoire(int mn,int mx);

/*
BLABLABLABLABLABLABLABLABLABLABLA
BLABLABLABALBALABLABALBALABLABALB
*/
string ChoisirMots(std::string mots[],int tailleTableau);

/*
BLABLABLABLABLABLABLABLABLABLABLA
BLABLABLABALBALABLABALBALABLABALB
*/
bool TestCaractere(char lettre, string mot, string &motCache);

/*
BLABLABLABLABLABLABLABLABLABLABLA
BLABLABLABALBALABLABALBALABLABALB
*/
int Life(bool reponse, int &vie);











#endif // FONCTION_H_INCLUDED
